# This file was generated by GoReleaser. DO NOT EDIT.
class Muiblok < Formula
  desc "https://github.com/apjames93/mui-storyblok-cli"
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/apjames93/mui-storyblok-cli/releases/download/v0.1.0/mui-storyblok-cli_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "7c57e108974e83f6ccecb030eae614e99bc52d0f36f73071b8a1ce88b97f9fcd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/apjames93/mui-storyblok-cli/releases/download/v0.1.0/mui-storyblok-cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "a16bcaf5f30bfebe0f944c874d5fcf9219ffeb0c5325f65d5d9aad0eb7ffb6e7"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "muiblok"
  end
end
